"""module_5_ai_grading_fix

Revision ID: 3fbae6b4a9ae
Revises: ca6361356701
Create Date: 2026-06-01 14:51:16.282011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fbae6b4a9ae'
down_revision: Union[str, Sequence[str], None] = 'ca6361356701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iot_scales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('mac_address', sa.String(length=50), nullable=False),
    sa.Column('panchayat_id', sa.Integer(), nullable=True),
    sa.Column('paired_collector_id', sa.Integer(), nullable=True),
    sa.Column('battery_level', sa.Float(), nullable=True),
    sa.Column('is_tampered', sa.Boolean(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['paired_collector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['panchayat_id'], ['panchayats.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mac_address')
    )
    op.create_index(op.f('ix_iot_scales_id'), 'iot_scales', ['id'], unique=False)
    op.create_index(op.f('ix_iot_scales_serial_number'), 'iot_scales', ['serial_number'], unique=True)
    op.create_table('ai_grading_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('collector_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('contamination_rate', sa.Float(), nullable=True),
    sa.Column('plastic_types', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['collector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_grading_logs_id'), 'ai_grading_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_grading_logs_transaction_id'), 'ai_grading_logs', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_grading_logs_transaction_id'), table_name='ai_grading_logs')
    op.drop_index(op.f('ix_ai_grading_logs_id'), table_name='ai_grading_logs')
    op.drop_table('ai_grading_logs')
    op.drop_index(op.f('ix_iot_scales_serial_number'), table_name='iot_scales')
    op.drop_index(op.f('ix_iot_scales_id'), table_name='iot_scales')
    op.drop_table('iot_scales')
    # ### end Alembic commands ###
