"""add depot fields to zones

Revision ID: 4576a3b6da32
Revises: 59bc2954d176
Create Date: 2026-04-19 16:48:48.219590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4576a3b6da32'
down_revision: Union[str, Sequence[str], None] = '59bc2954d176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Use batch_alter_table for safer column additions
    with op.batch_alter_table('zones') as batch_op:
        try:
            batch_op.add_column(
                sa.Column('depot_lat', sa.Float(), nullable=True)
            )
        except Exception:
            pass
        try:
            batch_op.add_column(
                sa.Column('depot_lng', sa.Float(), nullable=True)
            )
        except Exception:
            pass
        try:
            batch_op.add_column(
                sa.Column('depot_address', sa.String(length=500), nullable=True)
            )
        except Exception:
            pass

    try:
        op.drop_table('seed_metadata')
    except Exception:
        pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zones', 'depot_address')
    op.drop_column('zones', 'depot_lng')
    op.drop_column('zones', 'depot_lat')
    op.create_table('seed_metadata',
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('seeded_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('seed_metadata_pkey'))
    )
    # ### end Alembic commands ###
