"""add news_feed table

Revision ID: 73b51ca1d573
Revises: 513b4ac37b4d
Create Date: 2026-04-25 23:15:28.463307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73b51ca1d573'
down_revision: Union[str, Sequence[str], None] = '513b4ac37b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('tag', sa.String(length=50), nullable=True),
    sa.Column('tag_color', sa.String(length=20), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_feed_id'), 'news_feed', ['id'], unique=False)
    op.drop_table('seed_metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seed_metadata',
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('seeded_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('seed_metadata_pkey'))
    )
    op.drop_index(op.f('ix_news_feed_id'), table_name='news_feed')
    op.drop_table('news_feed')
    # ### end Alembic commands ###
