"""add_fk_indexes

Revision ID: a86297312417
Revises: 73b51ca1d573
Create Date: 2026-05-18 23:09:58.076163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a86297312417'
down_revision: Union[str, Sequence[str], None] = '73b51ca1d573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bin_reports_bin_id'), 'bin_reports', ['bin_id'], unique=False)
    op.create_index(op.f('ix_bin_reports_verified_by'), 'bin_reports', ['verified_by'], unique=False)
    op.create_index(op.f('ix_recycler_bids_recycler_id'), 'recycler_bids', ['recycler_id'], unique=False)
    op.create_index(op.f('ix_shg_reports_bin_id'), 'shg_reports', ['bin_id'], unique=False)
    op.create_index(op.f('ix_shg_reports_shg_user_id'), 'shg_reports', ['shg_user_id'], unique=False)
    op.create_index(op.f('ix_shg_reports_zone_id'), 'shg_reports', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shg_reports_zone_id'), table_name='shg_reports')
    op.drop_index(op.f('ix_shg_reports_shg_user_id'), table_name='shg_reports')
    op.drop_index(op.f('ix_shg_reports_bin_id'), table_name='shg_reports')
    op.drop_index(op.f('ix_recycler_bids_recycler_id'), table_name='recycler_bids')
    op.drop_index(op.f('ix_bin_reports_verified_by'), table_name='bin_reports')
    op.drop_index(op.f('ix_bin_reports_bin_id'), table_name='bin_reports')
    # ### end Alembic commands ###
