"""v3_mega_migration

Revision ID: ca6361356701
Revises: 0bfbb2495547
Create Date: 2026-06-01 12:36:37.087940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca6361356701'
down_revision: Union[str, Sequence[str], None] = '0bfbb2495547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('panchayats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('sarpanch_name', sa.String(length=100), nullable=True),
    sa.Column('sarpanch_phone', sa.String(length=20), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('total_houses', sa.Integer(), nullable=True),
    sa.Column('target_houses', sa.Integer(), nullable=True),
    sa.Column('border_mapping', sa.JSON(), nullable=True),
    sa.Column('language_pref', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_panchayats_id'), 'panchayats', ['id'], unique=False)
    op.create_index(op.f('ix_panchayats_name'), 'panchayats', ['name'], unique=False)
    op.create_table('attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collector_id', sa.Integer(), nullable=False),
    sa.Column('panchayat_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('check_out_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['collector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['panchayat_id'], ['panchayats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendances_collector_id'), 'attendances', ['collector_id'], unique=False)
    op.create_index(op.f('ix_attendances_date'), 'attendances', ['date'], unique=False)
    op.create_index(op.f('ix_attendances_id'), 'attendances', ['id'], unique=False)
    # --- Drop dependent tables before bins (CASCADE handles any remaining FKs) ---
    # shg_reports and bin_reports reference bins.id — drop them first
    op.execute('DROP TABLE IF EXISTS shg_reports CASCADE')
    op.execute('DROP TABLE IF EXISTS bin_reports CASCADE')

    # Now drop bins itself (CASCADE removes any stray FK constraints)
    op.execute('DROP INDEX IF EXISTS idx_bins_location')
    op.execute('DROP INDEX IF EXISTS ix_bins_id')
    op.execute('DROP TABLE IF EXISTS bins CASCADE')

    # collections.bin_id and route_stops.bin_id — these columns may or may not
    # exist in the live DB depending on migration history. Guard with try/except.
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    collections_cols = [c['name'] for c in inspector.get_columns('collections')]
    if 'bin_id' in collections_cols:
        # Drop FK constraint if it still exists
        fks = [fk['name'] for fk in inspector.get_foreign_keys('collections')]
        if 'collections_bin_id_fkey' in fks:
            op.drop_constraint('collections_bin_id_fkey', 'collections', type_='foreignkey')
        idxs = [ix['name'] for ix in inspector.get_indexes('collections')]
        if 'ix_collections_bin_id' in idxs:
            op.drop_index('ix_collections_bin_id', table_name='collections')
        op.drop_column('collections', 'bin_id')

    route_stop_cols = [c['name'] for c in inspector.get_columns('route_stops')]
    if 'bin_id' in route_stop_cols:
        fks = [fk['name'] for fk in inspector.get_foreign_keys('route_stops')]
        if 'route_stops_bin_id_fkey' in fks:
            op.drop_constraint('route_stops_bin_id_fkey', 'route_stops', type_='foreignkey')
        op.drop_column('route_stops', 'bin_id')
    op.add_column('users', sa.Column('qr_status', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('lng', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('socio_category', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('panchayat_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_users_house_id'), 'users', type_='unique')
    op.create_foreign_key(None, 'users', 'panchayats', ['panchayat_id'], ['id'])
    op.add_column('zones', sa.Column('panchayat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'zones', 'panchayats', ['panchayat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zones', type_='foreignkey')
    op.drop_column('zones', 'panchayat_id')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_unique_constraint(op.f('uq_users_house_id'), 'users', ['house_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'panchayat_id')
    op.drop_column('users', 'socio_category')
    op.drop_column('users', 'lng')
    op.drop_column('users', 'lat')
    op.drop_column('users', 'qr_status')
    op.add_column('route_stops', sa.Column('bin_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('route_stops_bin_id_fkey'), 'route_stops', 'bins', ['bin_id'], ['id'])
    op.add_column('collections', sa.Column('bin_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('collections_bin_id_fkey'), 'collections', 'bins', ['bin_id'], ['id'])
    op.create_index(op.f('ix_collections_bin_id'), 'collections', ['bin_id'], unique=False)
    op.create_table('bin_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bin_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('fill_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('waste_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('urgency', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ai_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ai_observations', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reporter_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('reporter_lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('verified_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bin_id'], ['bins.id'], name=op.f('bin_reports_bin_id_fkey')),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name=op.f('bin_reports_verified_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bin_reports_pkey'))
    )
    op.create_index(op.f('ix_bin_reports_verified_by'), 'bin_reports', ['verified_by'], unique=False)
    op.create_index(op.f('ix_bin_reports_id'), 'bin_reports', ['id'], unique=False)
    op.create_index(op.f('ix_bin_reports_bin_id'), 'bin_reports', ['bin_id'], unique=False)
    op.create_table('shg_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shg_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('zone_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('plastic_collected_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('plastic_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('fill_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('collection_point', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bin_id'], ['bins.id'], name=op.f('shg_reports_bin_id_fkey')),
    sa.ForeignKeyConstraint(['shg_user_id'], ['users.id'], name=op.f('shg_reports_shg_user_id_fkey')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('shg_reports_zone_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('shg_reports_pkey'))
    )
    op.create_index(op.f('ix_shg_reports_zone_id'), 'shg_reports', ['zone_id'], unique=False)
    op.create_index(op.f('ix_shg_reports_shg_user_id'), 'shg_reports', ['shg_user_id'], unique=False)
    op.create_index(op.f('ix_shg_reports_id'), 'shg_reports', ['id'], unique=False)
    op.create_index(op.f('ix_shg_reports_bin_id'), 'shg_reports', ['bin_id'], unique=False)
    op.create_table('bins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('label', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('zone_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('empty', 'inactive', 'low', 'medium', 'high', 'full', 'overflow', 'partial', 'critical', name='binstatus'), autoincrement=False, nullable=False),
    sa.Column('fill_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('capacity_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('last_collected', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('bins_zone_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bins_pkey'))
    )
    op.create_index(op.f('ix_bins_id'), 'bins', ['id'], unique=False)
    op.create_index(op.f('idx_bins_location'), 'bins', ['location'], unique=False, postgresql_using='gist')
    op.drop_index(op.f('ix_attendances_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_date'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_collector_id'), table_name='attendances')
    op.drop_table('attendances')
    op.drop_index(op.f('ix_panchayats_name'), table_name='panchayats')
    op.drop_index(op.f('ix_panchayats_id'), table_name='panchayats')
    op.drop_table('panchayats')
    # ### end Alembic commands ###
